package com.ring.cloud.facade.crawl;

import lombok.Data;

import java.util.HashMap;
import java.util.Map;

@Data
public class CommonLet {
    public static Map<String, String> letMap = new HashMap<>();

    static {
//        List<String> letType = Arrays.asList("平手","半球","一球","一球","一球","一球","一球","一球","一球","一球","一球",);
        letMap.put("平手", "0");

        letMap.put("平手/半球", "0.2");
        letMap.put("半球", "0.5");
        letMap.put("半球/一球", "0.7");
        letMap.put("一球", "1");
        letMap.put("一球/球半", "1.2");
        letMap.put("球半", "1.5");
        letMap.put("球半/两球", "1.7");
        letMap.put("两球", "2");
        letMap.put("两球/两球半", "2.2");
        letMap.put("两球半", "2.5");
        letMap.put("两球半/三球", "2.7");
        letMap.put("三球", "3");
        letMap.put("三球/三球半", "3.2");
        letMap.put("三球半", "3.5");
        letMap.put("三球半/四球", "3.7");
        letMap.put("四球", "4");
        letMap.put("四球/四球半", "4.2");
        letMap.put("四球半", "4.5");
        letMap.put("四球半/五球", "4.7");
        letMap.put("五球", "5");
        letMap.put("五球/五球半", "5.2");
        letMap.put("五球半", "5.5");
        letMap.put("五球半/六球", "5.7");
        letMap.put("六球", "6");
        letMap.put("六球/六球半", "6.2");
        letMap.put("六球半", "6.5");
        letMap.put("六球半/七球", "6.7");
        letMap.put("七球", "7");
        letMap.put("七球/七球半", "7.2");
        letMap.put("七球半", "7.5");
        letMap.put("七球半/八球", "7.7");
        letMap.put("八球", "8");
        letMap.put("八球/八球半", "8.2");
        letMap.put("八球半", "8.5");
        letMap.put("八球半/九球", "8.7");
        letMap.put("九球", "9");
        letMap.put("九球/九球半", "9.2");
        letMap.put("九球半", "9.5");

        letMap.put("受平手/半球", "+0.2");
        letMap.put("受半球", "+0.5");
        letMap.put("受半球/一球", "+0.7");
        letMap.put("受一球", "+1");
        letMap.put("受一球/球半", "+1.2");
        letMap.put("受球半", "+1.5");
        letMap.put("受球半/两球", "+1.7");
        letMap.put("受两球", "+2");
        letMap.put("受两球/两球半", "+2.2");
        letMap.put("受两球半", "+2.5");
        letMap.put("受两球半/三球", "+2.7");
        letMap.put("受三球", "++3");
        letMap.put("受三球/三球半", "+3.2");
        letMap.put("受三球半", "+3.5");
        letMap.put("受三球半/四球", "+3.7");
        letMap.put("受四球", "+4");
        letMap.put("受四球/四球半", "+4.2");
        letMap.put("受四球半", "+4.5");
        letMap.put("受四球半/五球", "+4.7");
        letMap.put("受五球", "+5");
        letMap.put("受五球/五球半", "+5.2");
        letMap.put("受五球半", "+5.5");
        letMap.put("受五球半/六球", "+5.7");
        letMap.put("受六球", "+6");
        letMap.put("受六球/六球半", "+6.2");
        letMap.put("受六球半", "+6.5");
        letMap.put("受六球半/七球", "+6.7");
        letMap.put("受七球", "+7");
        letMap.put("受七球/七球半", "+7.2");
        letMap.put("受七球半", "+7.5");
        letMap.put("受七球半/八球", "+7.7");
        letMap.put("受八球", "+8");
        letMap.put("受八球/八球半", "+8.2");
        letMap.put("受八球半", "+8.5");
        letMap.put("受八球半/九球", "+8.7");
        letMap.put("受九球", "+9");
        letMap.put("受九球/九球半", "+9.2");
        letMap.put("受九球半", "+9.5");

//        letMap.put("平手/半球", "0.25");
//        letMap.put("半球", "0.5");
//        letMap.put("半球/一球", "0.75");
//        letMap.put("一球", "1");
//        letMap.put("一球/球半", "1.25");
//        letMap.put("球半", "1.5");
//        letMap.put("球半/两球", "1.75");
//        letMap.put("两球", "2");
//        letMap.put("两球/两球半", "2.25");
//        letMap.put("两球半", "2.5");
//        letMap.put("两球半/三球", "2.75");
//        letMap.put("三球", "3");
//        letMap.put("三球/三球半", "3.25");
//        letMap.put("三球半", "3.5");
//        letMap.put("三球半/四球", "3.75");
//        letMap.put("四球", "4");
//        letMap.put("四球/四球半", "4.25");
//        letMap.put("四球半", "4.5");
//        letMap.put("四球半/五球", "4.75");
//        letMap.put("五球", "5");
//        letMap.put("五球/五球半", "5.25");
//        letMap.put("五球半", "5.5");
//        letMap.put("五球半/六球", "5.75");
//        letMap.put("六球", "6");
//        letMap.put("六球/六球半", "6.25");
//        letMap.put("六球半", "6.5");
//        letMap.put("六球半/七球", "6.75");
//        letMap.put("七球", "7");
//        letMap.put("七球/七球半", "7.25");
//        letMap.put("七球半", "7.5");
//        letMap.put("七球半/八球", "7.75");
//        letMap.put("八球", "8");
//        letMap.put("八球/八球半", "8.25");
//        letMap.put("八球半", "8.5");
//        letMap.put("八球半/九球", "8.75");
//        letMap.put("九球", "9");
//        letMap.put("九球/九球半", "9.25");
//        letMap.put("九球半", "9.5");
//
//        letMap.put("受平手/半球", "+0.25");
//        letMap.put("受半球", "+0.5");
//        letMap.put("受半球/一球", "+0.75");
//        letMap.put("受一球", "+1");
//        letMap.put("受一球/球半", "+1.25");
//        letMap.put("受球半", "+1.5");
//        letMap.put("受球半/两球", "+1.75");
//        letMap.put("受两球", "+2");
//        letMap.put("受两球/两球半", "+2.25");
//        letMap.put("受两球半", "+2.5");
//        letMap.put("受两球半/三球", "+2.75");
//        letMap.put("受三球", "++3");
//        letMap.put("受三球/三球半", "+3.25");
//        letMap.put("受三球半", "+3.5");
//        letMap.put("受三球半/四球", "+3.75");
//        letMap.put("受四球", "+4");
//        letMap.put("受四球/四球半", "+4.25");
//        letMap.put("受四球半", "+4.5");
//        letMap.put("受四球半/五球", "+4.75");
//        letMap.put("受五球", "+5");
//        letMap.put("受五球/五球半", "+5.25");
//        letMap.put("受五球半", "+5.5");
//        letMap.put("受五球半/六球", "+5.75");
//        letMap.put("受六球", "+6");
//        letMap.put("受六球/六球半", "+6.25");
//        letMap.put("受六球半", "+6.5");
//        letMap.put("受六球半/七球", "+6.75");
//        letMap.put("受七球", "+7");
//        letMap.put("受七球/七球半", "+7.25");
//        letMap.put("受七球半", "+7.5");
//        letMap.put("受七球半/八球", "+7.75");
//        letMap.put("受八球", "+8");
//        letMap.put("受八球/八球半", "+8.25");
//        letMap.put("受八球半", "+8.5");
//        letMap.put("受八球半/九球", "+8.75");
//        letMap.put("受九球", "+9");
//        letMap.put("受九球/九球半", "+9.25");
//        letMap.put("受九球半", "+9.5");
    }

}
