server.port=8888
server.servlet.context-path=/crawl
spring.jackson.ext.serialization.write-long-as-string=true
spring.jackson.ext.serialization.write-double-as-string=true
spring.jackson.ext.serialization.write-null-array-as-empty-string=true
spring.jackson.ext.serialization.write-null-string-as-empty-string=true

#定时任务 ip domain
ml.ip.new.query.enabled=false
ml.ip.new.query.delay=20

#proxy config
#单个代理地址
ml.client.proxy.url=http://v2.api.juliangip.com/unlimited/getips?auto_white=1&num=10&pt=1&result_type=text&split=1&trade_no=5146320972443658&sign=6004c288e00c37af81095e47defee8d7
#最大重试次数，包含首次
ml.client.proxy.maxRetry=5
#重试间隔
ml.client.proxy.intervalSec=5
#有效时间 单位：秒
ml.client.proxy.valid.time=30

#pang config
#地址
ml.client.desc.ip.pangzhan=https://chapangzhan.com
#最大重试次数，包含首次
ml.client.pang.maxRetry=10
#重试间隔
ml.client.pang.intervalSec=4

#webclient超时配置：10秒（连接/读写/响应统一超时）
ml.client.proxy.connect.timeout=10

#文件路径
ml.client.ip.file.path=D:\\crawl\\xml
ml.client.ip.file.name.prefix=ip

#ip domain目标网址
ml.client.desc.ip.domain=https://site.ip138.com
ml.client.desc.ip.page.infix=index/querybyip

#ip domain 大ip记录
ml.client.ip.large.mark=true
ml.client.ip.large.file.path=D:\\crawl\\largeIp.txt

#ehcache cache config
#spring.cache.type=ehcache
#spring.cache.cache-names=ehcache
#spring.cache.ehcache.config=classpath:ehcache.xml

##thread pool config
thread.pool.core-pool-size=20
thread.pool.max-pool-size=30
thread.pool.queue-capacity=500
thread.pool.thread-name-prefix=thread-pool-

## quatz start
#线程池实现类
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
#线程池线程数
spring.quartz.properties.org.quartz.threadPool.threadCount=10
#线程池优先级：可以是Thread.MIN_PRIORITY（即1）和Thread.MAX_PRIORITY（这是10）之间的任何int 。默认值为Thread.NORM_PRIORITY（5）
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
#线程池线程继承Context ClassLoader初始化线程
spring.quartz.properties.org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true
## quatz end