server.port=8888
server.servlet.context-path=/crawl
spring.jackson.ext.serialization.write-long-as-string=true
spring.jackson.ext.serialization.write-double-as-string=true
spring.jackson.ext.serialization.write-null-array-as-empty-string=true
spring.jackson.ext.serialization.write-null-string-as-empty-string=true

#ip采集自定义配置-------------------------------------------------------------------------------
#定时任务 指定ip开关和定时规则
ml.ip.specify.query.enabled=false
ml.ip.specify.query.cron=0 0 * * * ?
#定时任务 最新查询mix 开关和间隔时间 单位：秒
ml.ip.new.query.enabled=false
ml.ip.new.query.delay=10
#定时任务 最新查询ai domain 开关和间隔时间 单位：秒
ml.domain.query.ai.new.enabled=false
ml.domain.query.ai.new.delay=10

#proxy 地址
ml.client.proxy.url=http://v2.api.juliangip.com/unlimited/getips?auto_white=1&num=10&pt=1&result_type=text&split=1&trade_no=5146320972443658&sign=6004c288e00c37af81095e47defee8d7
#pang 目标地址
ml.client.desc.ip.pangzhan=https://chapangzhan.com
#subdomain地址
ml.client.domain.subdomain=https://chaziyu.com
#ip domain地址
ml.client.desc.ip.domain=https://site.ip138.com
#ai domain地址
ml.client.desc.ai.domain=https://www.aizhan.com/cha
#domain 导出文件路径和全量导出完整路径
ml.client.domain.file.path=D:\\crawl\\xml\\dom
ml.client.domain.file.allname=D:\\crawl\\xml\\dom\\all_domain.csv
#全局ip 生成文件路径和文件前缀
ml.client.ip.file.path=D:\\crawl\\xml\\ip
ml.client.ip.file.name.prefix=ip

#-------------------------------------------------------------------------------------------
#关键词采集 站点 逗号分隔
ml.client.keyword.desc.site=baidu.com,so.com
#ml.client.keyword.desc.site=bing.com,baidu.com,so.com,google.com,yandex.com
#文件路径
ml.client.keyword.output.path=D:\\crawl\\keyword
# Redis 连接
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.database=0

# 布隆过滤器配置
bloom.filter.expectedInsertions=100000000
bloom.filter.falseProbability=0.0001
#-------------------------------------------------------------------------------------------

#ehcache cache config
#spring.cache.type=ehcache
#spring.cache.cache-names=ehcache
#spring.cache.ehcache.config=classpath:ehcache.xml

##thread pool config
thread.pool.core-pool-size=20
thread.pool.max-pool-size=30
thread.pool.queue-capacity=500
thread.pool.thread-name-prefix=thread-pool-

## quatz start
#线程池实现类
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
#线程池线程数
spring.quartz.properties.org.quartz.threadPool.threadCount=10
#线程池优先级：可以是Thread.MIN_PRIORITY（即1）和Thread.MAX_PRIORITY（这是10）之间的任何int 。默认值为Thread.NORM_PRIORITY（5）
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
#线程池线程继承Context ClassLoader初始化线程
spring.quartz.properties.org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true
## quatz end